# Generated by Django 2.1.1 on 2018-11-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
