# Generated by Django 2.1.1 on 2018-11-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='voters',
            field=models.ManyToManyField(related_name='_profile_voters_+', to='user_profile.Profile'),
        ),
    ]
